name: dddd-can_can_need

on:
  push:
    branches:
      - Yosunair
  workflow_dispatch:
  
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 无论什么勾八东西最新的总是最好的
        uses: actions/setup-node@v2
        with:
          node-version: "19.4.0"
      - name: 把这勾八依赖东西缓存了
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: 叼毛修复WDNMD
        run: PATH="${PATH}:/home/runner/work/Yosunair.github.io/Yosunair.github.io/node_modules/hexo/bin"
             sudo npm install hexo
             sudo npm install hexo -g
      - name: 把这些需要的勾八依赖也给安装上
        run: sudo npm install -g
             sudo npm install 
      - name: 叼毛行为WDNMD
        run: sudo echo NMBWCNM
             sudo chmod -R 777 /home/runner/work/Yosunair.github.io/Yosunair.github.io
             sudo chmod -R 777 /home/runner/work/Yosunair.github.io
             sudo chmod -R 777 /home
             sudo chmod -R 777 /root
      - name: 把这些勾八东西处理完了开始整合
        run: sudo npm run build
      - name: 勾八事情全部干完了就完事结束撒花了
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
